### ISSUE TITLE
Template selection dialog keeps shifting on selection - Ubuntu 

### ISSUE THREAD

**Issue by avneenathani** [BuildmLearn/BuildmLearn-Toolkit#49]
The template selection dialog needs a little tweaking. When a template is selected the selection box shifts to the right. 
Screenshot: Red dashed line shows the shifting.
https://www.dropbox.com/s/ynu7y3dcngdbvq3/ScreenShot.png?dl=0

**Comment by ravirnjn88** [comment]
Bug Fixed.
Screen-shot : https://www.dropbox.com/s/7vrn6c7ap2x91et/BuildmLearn.jpg?dl=0
