### ISSUE TITLE
untracked files shown when installing to a custom folder 

### ISSUE THREAD

**Issue by harishnavnit** [BuildmLearn/BuildmLearn-Toolkit#51]
untracked files are shown(i.e the build folder) when the build folder is not included in .gitignore. I used the following cmake command 

cmake ../ -DCMAKE_BUILD_TYPE="relase" -DCMAKE_PREFIX_PATH=/prefix/path -DCMAKE_INSTALL_PREFIX=/install/prefix=/install/prefix/path -DUSE_QT_5="ON"

**Comment by martinrotter** [comment]
The given command is just example. You can (and should) place your build folder completely out of build tree, therefore use so-called "out-of-source" build approach.

**Comment by harishnavnit** [comment]
oh okay. I think this can be mentioned in the CMakeLists.txt too ? I personally am used to having the build inside the source tree. Besides, I think adding the build folder to .gitignore does work. The change doesn't necessarily have to go in though :)

**Comment by harishnavnit** [comment]
@martinrotter is there an IRC channel where you guys hang out ?

**Comment by croozeus** [comment]
@harishnavnit No there is no active IRC for BuildmLearn. We prefer you discuss everything in the mailing list: groups.google.com/forum/#!forum/buildmlearn
