### ISSUE TITLE
Unable to play the sound file

### ISSUE THREAD

**Issue by vasishtaguntupalli** [BuildmLearn/BuildmLearn-Toolkit#53]
When i click on the listen button ( spellings template) during simulation i get a pop up message saying "Sound cannot be played on this platform because sound file was not downloaded" , please tel me how to resolve this issue.

**Comment by ravirnjn88** [comment]
Api(http://mary.dfki.de) used to translate text to speech is not working.

**Comment by martinrotter** [comment]
Yes, the service is down. I will need to find replacement.

2015-03-07 16:26 GMT+01:00 Ravi Ranjan <notifications@github.com>:

**Comment by martinrotter** [comment]
Checked the proposed fix.
