### ISSUE TITLE
Quiz App Advancement

### ISSUE THREAD

**Issue by varunpdr** [BuildmLearn/BuildmLearn-Toolkit#75]
The app has poor GUI  and can be improved. The following features can be change in the app.
1) There is no back button for going to earlier question.
2) Timer for quiz can be implemented.
3) There can be a sliding drawer which would show no of question and Attempted question will be marked by green, unattempted by orange. and user can navigate directly to any question by clicking on the question.
4) The app can be also improved by adding questions on photos not just text as shown. Actually photo convey more than words. 
5) More better background and different types of question can be include in the app.

I would like to work on these features. Where is the code for existing app. I am able to find only .apk package of  this app.

Thank you
Varun Pidyar

**Comment by martinrotter** [comment]
Note that if you improve the app itself, you also must improve the template so that both components MATCH each other.

https://github.com/BuildmLearn/Toolkit-mobile-templates
